/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "standalone",
  skipTrailingSlashRedirect: true,
  transpilePackages: [
    "msw",
    "@mswjs/interceptors",
    "@open-draft/deferred-promise",
    "@open-draft/logger",
    "@open-draft/until",
    "headers-polyfill",
    "is-node-process",
    "outvariant",
    "rettime",
    "strict-event-emitter",
    "until-async",
    "@radix-ui/number",
    "@radix-ui/primitive",
    "@radix-ui/react-accordion",
    "@radix-ui/react-alert-dialog",
    "@radix-ui/react-arrow",
    "@radix-ui/react-aspect-ratio",
    "@radix-ui/react-avatar",
    "@radix-ui/react-checkbox",
    "@radix-ui/react-collapsible",
    "@radix-ui/react-collection",
    "@radix-ui/react-compose-refs",
    "@radix-ui/react-context",
    "@radix-ui/react-context-menu",
    "@radix-ui/react-dialog",
    "@radix-ui/react-direction",
    "@radix-ui/react-dismissable-layer",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-focus-guards",
    "@radix-ui/react-focus-scope",
    "@radix-ui/react-hover-card",
    "@radix-ui/react-id",
    "@radix-ui/react-label",
    "@radix-ui/react-menu",
    "@radix-ui/react-menubar",
    "@radix-ui/react-navigation-menu",
    "@radix-ui/react-popover",
    "@radix-ui/react-popper",
    "@radix-ui/react-portal",
    "@radix-ui/react-presence",
    "@radix-ui/react-primitive",
    "@radix-ui/react-progress",
    "@radix-ui/react-radio-group",
    "@radix-ui/react-roving-focus",
    "@radix-ui/react-scroll-area",
    "@radix-ui/react-select",
    "@radix-ui/react-separator",
    "@radix-ui/react-slider",
    "@radix-ui/react-slot",
    "@radix-ui/react-switch",
    "@radix-ui/react-tabs",
    "@radix-ui/react-toast",
    "@radix-ui/react-toggle",
    "@radix-ui/react-toggle-group",
    "@radix-ui/react-tooltip",
    "@radix-ui/react-use-callback-ref",
    "@radix-ui/react-use-controllable-state",
    "@radix-ui/react-use-effect-event",
    "@radix-ui/react-use-escape-keydown",
    "@radix-ui/react-use-is-hydrated",
    "@radix-ui/react-use-layout-effect",
    "@radix-ui/react-use-previous",
    "@radix-ui/react-use-rect",
    "@radix-ui/react-use-size",
    "@radix-ui/react-visually-hidden",
    "@radix-ui/rect",
    "swagger-client",
    "graphql",
    "immer",
    "immutable",
    "highlight.js",
    "react-syntax-highlighter",
    "remarkable",
    "randexp",
    "drange",
    "autolinker",
    "dompurify",
    "js-yaml",
    "zenscroll",
    "@tanstack/query-core",
    "@tanstack/react-query",
    "@tanstack/react-table",
    "@tanstack/react-virtual",
    "@tanstack/table-core",
    "@tanstack/virtual-core",
    "lucide-react",
    "react-hook-form",
    "@hookform/resolvers",
    "swagger-ui-react",
    "tailwind-merge",
    "xlsx",
    "zod",
  ],
  turbopack: {},
  compiler: {
    removeConsole:
      process.env.NODE_ENV === "production"
        ? {
            exclude: ["error", "warn"],
          }
        : false,
  },
  reactCompiler: false,
  experimental: {
    viewTransition: true,
    cpus: 2,
  },
};

export default nextConfig;
