allowBuilds:
  '@scarf/scarf': set this to true or false
  '@tree-sitter-grammars/tree-sitter-yaml': set this to true or false
  core-js-pure: set this to true or false
  msw: set this to true or false
  sharp: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-json: set this to true or false
  unrs-resolver: set this to true or false
